version: '3.9'
services:
  postgres_database:
    image: 'postgres:14.1-alpine'
    restart: 'always'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'
    networks:
      news-app-prod:
  minio:
    image: minio/minio:latest
    command: server --console-address ":${MINIO_HELTH_PORT}" /data/
    ports:
      - '${MINIO_MAIN_PORT}:${MINIO_MAIN_PORT}'
      - '${MINIO_HELTH_PORT}:${MINIO_HELTH_PORT}'
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
    volumes:
      - minio-storage:/data
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:${MINIO_MAIN_PORT}/minio/health/live',
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      news-app-prod:
  api-app:
    restart: always
    image: node:18
    ports:
      - '8080:8080'
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    volumes:
      - ./../:/app
    command: 'npm run start:prod'
    networks:
      news-app-prod:
  frontend:
    restart: always
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./../fe-news-app:/app
      - ./../.env:/app/.env
    command: 'npm run start:prod'
    networks:
      news-app-prod:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-app
      - frontend
    networks:
      news-app-prod:
volumes:
  minio-storage:
networks:
  news-app-prod:
